FROM openjdk:8-jdk-alpine
RUN apk add --update mysql mysql-client
ADD target/spring-boot-app.jar spring-boot-app.jar
EXPOSE 8081
ENV MYSQL_ROOT_PASSWORD=root
ENV MYSQL_DATABASE=test
ENV MYSQL_USER=test_user
ENV MYSQL_PASSWORD=test_password
ENTRYPOINT ["java","-jar","/spring-boot-app.jar"]